/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function arrsacLine(x: Array<number>, y: Array<number>, options?: ArrsacOptions | undefined | null): ArrsacResult | null

export interface ArrsacOptions {
  inlierThreshold?: number
  minSlope?: number
  maxSlope?: number
  minIntercept?: number
  maxIntercept?: number
}

export interface ArrsacResult {
  slope: number
  intercept: number
  inliers: Array<number>
  r2All: number
  r2Inliers: number
  rmseAll: number
  rmseInliers: number
  madAll: number
  madInliers: number
  iqrAll: number
  iqrInliers: number
  inlierRatio: number
  numInliers: number
  numPoints: number
  maxAbsResidual: number
  threshold: number
}
